### ISSUE TITLE
File cache driver not working

### ISSUE THREAD

**Issue by Mircea-Ciuchea** [patrickbrouwers/Laravel-Doctrine#3]
In my .env file I have `CACHE_DRIVER=file` and when try to schema:update command i get the following error:
`[InvalidArgumentException] 
Invalid argument given, PhpFileCache only allows objects that implement __set_state() and fully support var_export(). You can use the FilesystemCache to save arbitrary object graphs using serialize()/deserialize().`
My workaround was to replace PhpFileCache with FilesystemCache in `Brouwers\LaravelDoctrine\Configuration\Cache\FileCacheProvider ` register method, but a `__set_state()` method should be implemented.

**Comment by patrickbrouwers** [comment]
`FilesystemCache` does indeed work. Fixed in v1.0.2 .

Not a lot to find about file caching in the doctrine docs. Bot PhpFileCache and FilesystemCache don't get listed in their docs: http://doctrine-orm.readthedocs.org/en/latest/reference/caching.html

Did you ever look at Redis? I really like it, use it for queues, sessions, cache and broadcasting.

**Comment by Mircea-Ciuchea** [comment]
I was excited about the new laravel/doctrine package and didn't set up Redis, just go with the defaults and this problem pop-up. 

Also a minimum-stability should be added in composer.json to avoid doctrine/migrations dependency warning on installation. 

Besides this everything worked well and I am really glad that finally a laravel 5 doctrine bridge came up. Good work!

**Comment by patrickbrouwers** [comment]
I understand :)

Don't want to put minimum-stability on dev, because I only want stable releases of Doctrine ORM. If you don't provide a minimum-stability it's automatically set to stable.
I don't get any warnings when installing it though. On second thought I don't even use doctrine/migrations (yet), so I will remove the dependency for now anyway.

Great to hear everything works well. Thanks!
